behaviors:
  race_behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      num_layers: 2
      hidden_units: 128
      normalize: false
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 2000
